### ISSUE TITLE
removing files

### ISSUE THREAD

**Issue by kilroywh** [Molecular-Nanophotonics/TrackerLab#12]
![Removing Error](https://user-images.githubusercontent.com/59698171/90389119-45897880-e089-11ea-944b-57c94ae95189.PNG)
can't remove files when current file is selected (also not possible with mulitple file selection)

**Comment by NicolaSoeker** [comment]
This issue is connected to the ram issue in a way

It is because there is a clear image function and it has code from old overlay.
