### ISSUE TITLE
TackerLab crashes if more than 12 files are batched

### ISSUE THREAD

**Issue by NicolaSoeker** [Molecular-Nanophotonics/TrackerLab#14]
I used 20 of Bennis files and batched them. All the csvs are saved correctly. After that the python kernel crashes and does not resopnd anymore. The kernel has to be shut down externaly.

**Comment by kilroywh** [comment]
Happens after updating conda, already also after 12 files and for batch conversions of tdms files

**Comment by NicolaSoeker** [comment]
This issue is connected to the RAM issue
