### ISSUE TITLE
Trackerlab Crashes

### ISSUE THREAD

**Issue by kilroywh** [Molecular-Nanophotonics/TrackerLab#7]
TrackerLab crahses/stopps working with batch convertion to hdf5 (or csv).
That happens when multiple files are converted and when one file is not as long as the others (in my case 1000 Frames long)
The error appears as shown in the image
![Error](https://user-images.githubusercontent.com/59698171/89406005-c1480480-d71c-11ea-91df-88abbaa721d1.PNG)

**Comment by NicolaSoeker** [comment]
i guess this is connencted to the ram issue. Please refere to the ram issue thread. closed.
